/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.io.*;
import java.util.*;

public
class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(yal2jvm p, int id) {
    super(p, id);
  }

  public void process(BufferedWriter s,SymbolTable st,String funcName){
      if(children != null) {
        for (int i = 0; i < children.length; ++i) {
          SimpleNode n = (SimpleNode)children[i];
          if (n != null) {
            ((ASTArgument)n).process(s,st,funcName);
          }
        }
      }
    }
  }
/* JavaCC - OriginalChecksum=227b01c4beab7b51ee27fd1741abfc1a (do not edit this line) */
