/* Generated By:JJTree: Do not edit this line. ASTAccessElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccessElement extends SimpleNode {
  public ASTAccessElement(int id) {
    super(id);
  }

  public ASTAccessElement(grammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb6eff662d2a40e1a8a90928296bc90c (do not edit this line) */
