/* Generated By:JJTree: Do not edit this line. ASTAccessElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccessElement extends SimpleNode {
  public ASTAccessElement(int id) {
    super(id);
  }

  public ASTAccessElement(yal2jvm p, int id) {
    super(p, id);
  }
  public String toString() { return yal2jvmTreeConstants.jjtNodeName[id] +" "+ this.name; }
  

}
/* JavaCC - OriginalChecksum=5cb57520f1b7d6f77670f63c633c5392 (do not edit this line) */
