/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(grammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a16b5408eab606dfea561a2d04fedac7 (do not edit this line) */
