/* Generated By:JJTree: Do not edit this line. ASTIf.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.io.*;
import java.util.*;

public
class ASTIf extends SimpleNode {
  protected String telse;
  protected int stmtCounter=0;
  protected static int loopCounter = 0;

  public ASTIf(int id) {
    super(id);
  }

  public ASTIf(yal2jvm p, int id) {
    super(p, id);
  }

  public void setElse(String t){
    this.telse=t;
  }

  public void process(BufferedWriter s, SymbolTable st,String funcName){

try{
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        if(children[i].getClass().getName() == "ASTExprtest"){
        ASTExprtest n = (ASTExprtest)children[i];
        if (n != null) {
          n.process(s,st,funcName);
          }
        s.write("loop"+ loopCounter +"_end \n");
        }
      }
    }

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        if(children[i].getClass().getName() == "ASTStmtlst"){
        ASTStmtlst n = (ASTStmtlst)children[i];
        if (n != null) {
          n.process(s,st,funcName);
          }
          if(this.telse == "true"){
            if(this.stmtCounter == 0){
              s.write("goto loop" + loopCounter +"_next\n");
              s.write("loop"+ loopCounter +"_end:\n");
              this.stmtCounter++;
            }
            else if(this.stmtCounter == 1){
              s.write("loop"+ loopCounter +"_next:\n");
            }
          }else{
            s.write("loop"+ loopCounter +"_end:\n");
          }
        }
      }
    }

    loopCounter++;


  }catch (IOException e)
  {
    System.out.println("Exception ");
  }

  }

  public void lookForLocals(String func_name, SymbolTable st){
    if(children != null) {
      for (int i = 0; i < children.length; ++i) {
        if(children[i].getClass().getName() == "ASTStmtlst"){
        ASTStmtlst n = (ASTStmtlst)children[i];
        if (n != null) {
          n.lookForLocals(func_name,st);
        }
      }
    }
  }
  }


}
/* JavaCC - OriginalChecksum=4b3e4c231e0afc3d61129e3c066655a0 (do not edit this line) */
