/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.io.*;
import java.util.*;
import java.util.ArrayList;

public
class ASTModule extends SimpleNode {
  private static SymbolTable main_table;

  public ASTModule(int id) {
    super(id);
    this.main_table=new SymbolTable(this.name);

  }
  public String toString() { return yal2jvmTreeConstants.jjtNodeName[id] +" "+ this.name; }

  public ASTModule(yal2jvm p, int id) {
    super(p, id);
  }

  public void process(BufferedWriter s){

    try{
    s.write(".class public " + this.name + "\n");
    s.write(".super java/lang/Object\n");
  }
    catch (IOException e)
    {
      System.out.println("Exception ");

    }

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.process(s);
        }
      }
    }
  }

}
/* JavaCC - OriginalChecksum=9b9343e04f61c32fe112ea4c8db513ec (do not edit this line) */
