/* Generated By:JJTree: Do not edit this line. ASTScalarAccess.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTScalarAccess extends SimpleNode {
  public ASTScalarAccess(int id) {
    super(id);
  }

  public ASTScalarAccess(grammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4359e271abc64fc4fde6a924b71450b (do not edit this line) */
