/* Generated By:JJTree: Do not edit this line. ASTTerm.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTerm extends SimpleNode {
  private int element_value;
  private String signal;
  public ASTTerm(int id) {
    super(id);
  }

  public ASTTerm(grammar p, int id) {
    super(p, id);
  }

  public void setSignal(String signal){
    this.signal=signal;
  }

  public void setElementValue(String value){
    String finalValue;
    if(this.signal!=null)
    finalValue= this.signal +value;
    else
    finalValue=value;


    this.element_value=Integer.parseInt(finalValue);
  }

  @Override
  public String toString() {
    return grammarTreeConstants.jjtNodeName[id] +" "+ "element value:"+ this.element_value;
  }

}
/* JavaCC - OriginalChecksum=170cb74cc85d4b20c7823a847b360c09 (do not edit this line) */
