/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(grammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4dfa2ceb8912331eaafee15c636db949 (do not edit this line) */
