/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.io.*;
import java.util.*;

public
class ASTWhile extends SimpleNode {
  protected static int loopCounter = 0;
  public ASTWhile(int id) {
    super(id);
  }

  public ASTWhile(yal2jvm p, int id) {
    super(p, id);
  }


  public void process(BufferedWriter s, SymbolTable st,String funcName){
    try{
        s.write("loop" + loopCounter + ":\n");
        if (children != null) {
          for (int i = 0; i < children.length; ++i) {
            if(children[i].getClass().getName() == "ASTExprtest"){
            ASTExprtest n = (ASTExprtest)children[i];
            if (n != null) {
              n.process(s,st,funcName);
              }
            s.write("loop"+ loopCounter +"_end \n");
            }
          }
        }

        if (children != null) {
          for (int i = 0; i < children.length; ++i) {
            if(children[i].getClass().getName() == "ASTStmtlst"){
            ASTStmtlst n = (ASTStmtlst)children[i];
            if (n != null) {
              n.process(s,st,funcName);
              }
            }
          }
        }
        s.write("goto loop" + loopCounter+"\n");
        s.write("loop" + loopCounter + "_end:\n");
        loopCounter++;
      }catch (IOException e)
      {
        System.out.println("Exception ");
      }


  }

}
/* JavaCC - OriginalChecksum=6c1040b493c4b0c1271927efbf8f3a6f (do not edit this line) */
