/* Generated By:JavaCC: Do not edit this line. grammarTreeConstants.java Version 6.0_1 */
public interface grammarTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTVARLIST = 3;
  public int JJTELEMENT = 4;
  public int JJTSTMTLST = 5;
  public int JJTSTMT = 6;
  public int JJTASSIGN = 7;
  public int JJTLHS = 8;
  public int JJTRHS = 9;
  public int JJTARRAYSIZE = 10;
  public int JJTTERM = 11;
  public int JJTEXPRTEST = 12;
  public int JJTWHILE = 13;
  public int JJTIF = 14;
  public int JJTCALL = 15;
  public int JJTARGUMENTLIST = 16;
  public int JJTARGUMENT = 17;
  public int JJTACCESSELEMENT = 18;
  public int JJTARRAYACCESS = 19;
  public int JJTSCALARACCESS = 20;
  public int JJTINDEX = 21;
  public int JJTERROR_SKIPTO = 22;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Function",
    "Varlist",
    "Element",
    "Stmtlst",
    "Stmt",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "AccessElement",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
    "error_skipto",
  };
}
/* JavaCC - OriginalChecksum=f6a4ea6ec979d85bec90dcde078f4964 (do not edit this line) */
